### ISSUE TITLE
Add test coverage

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/activerecord-id_regions#4]
https://codeclimate.com/github/ManageIQ/activerecord-id_regions/coverage

We need more test coverage, at least on the lib/active_record/id_regions.rb file.  I have no idea how to test the lib/active_record/migration/id_regions.rb file.

**Comment by chrisarcand** [comment]
We should be able to write something similar to [how ActiveRecord tests it's migration DSL](https://github.com/rails/rails/blob/b81288541b6c8fe04082e4579e549bd71bc350dd/activerecord/test/cases/migration/helper.rb) to test the migration patches.
